

# class_mapping_7 = {
#     "1001": "pedestrian",     # "直立的人(person)",
#     "1002": "pedestrian",     # "形变的人(deformation)",
#     "1003": "pedestrian",     # "带附着物的人(person_w_things)",
#     "1004": "pedestrian",     # "复点位的人(person_inside)",
#     "2001": "pedestrian",     # "(推车的人)pushing",
#     "3001": "bicycle",        # "bicycle",
#     "3002": "motorcycle",     # "motorcycle",
#     "3003": "motorcycle",     # "tricycle",
#     "3004": "motorcycle",     # "其他二轮三轮车(others)",  !!!!!!!!
#     "3005": "motorcycle",     # "其他二轮三轮车(others)",  兼容处理
#     "4001": "rider",          # "骑自行车的人(cyclist)",
#     "4002": "rider",          # "骑摩托车的人(motorcyclist)",
#     "4003": "rider",          # "骑三轮车的人(tricyclist)",
#     "4004": "rider",          # "其他骑行者(others)",
#     "5001": "car",            # "(有棚机动车)shed",
#     "5002": "car",            # "(小型车)mini",
#     "5003": "car",            # "轿车(car)",
#     "5004": "car",            # "suv",
#     "5005": "car",            # "大面包车/拉货面包车(minibus)",
#     "5006": "car",            # "有棚非机动车(shed-non-motor)",
#     "6001": "truck",          # "带斗卡车(lorry)",
#     "6002": "truck",          # "异形车(machineshop)",
#     "6003": "truck",          # "箱形车(container)",
#     "6004": "truck",          # "皮卡",
#     "6005": "truck",          # "带斗大三轮",
#     "7001": "bus",            # "小巴(mini)",
#     "7002": "bus",            # "大巴(bus)",
#     "7003": "bus",            # "观光车(Sightseeing)",
#     "8001": "ignore",         # "自主移动障碍物(removable)",
#     "8002": "ignore",         # "不可自主移动障碍物(Resting)",
#     "9001": "ignore",         # "锥桶(conebucket)",
#     "9002": "ignore",         # "水马(waterhorse)",
#     "9003": "ignore",         # "防撞桶(bullbarrel)",
#     "9004": "ignore",         # "施工牌(construction)",
#     "9005": "ignore",         # "警示三角牌(warning)",
#     "10001": "ignore",        # "雨（含地面反弹）rain",
#     "10002": "ignore",        # "snow",
#     "10003": "ignore",        # "dust",
#     "10004": "ignore",        # "fog",
#     "10005": "ignore",        # "洒水车的水、车轮压过水池溅起的水花（water）",
#     "10006": "ignore",        # "噪点(other_noise)",
#     "10007": "ignore",        # "残影框excessive_layering",
#     "11001": "ignore",        # "other",
#     "12001": "ignore",        # "巡逻车 Patrolcar",
#     "12002": "ignore",        # "清扫车 Sweeper",
#     "12003": "ignore",        # "零售车 Retailcar",
# }

# class_map_refine = {
#             'Vehicle': 1, 'Pedestrian': 2, 'Cyclist': 3, 'Truck': 4,
#         }

# classname2id_7 = {
#     "car": 'Vehicle',
#     "truck": 'Truck',
#     "bus": 'Truck',
#     "rider": 'Cyclist',
#     "bicycle": 'Cyclist',
#     "pedestrian": 'Pedestrian',
#     "person": 'Pedestrian',
#     "motorcycle": 'Cyclist',
#     "ignore": 255,
# }


import numpy as np


# 原始标注类别如下，具体参见: http://wiki.zhidaohulian.com/pages/viewpage.action?pageId=151499541
# "1000":"人",
#     "1001": "直立的人(person)",
#     "1002":"形变的人(deformation)",
#     "1003":"带附着物的人(person_w_things)",
#     "1004":"复点位的人(person_inside)",
# "2000":"推车的人",
#     "2001":"(推车的人)pushing",
# "3000":"各种无人cycle",
#     "3001":"bicycle",
#     "3002":"motorcycle",
#     "3003":"tricycle",
#     "3004":"其他二轮三轮车(others)",
# "4000":"各种有人骑行者(rider)", 
#     "4001":"骑自行车的人(cyclist)",
#     "4002":"骑摩托车的人(motorcyclist)",
#     "4003":"骑三轮车的人(tricyclist)",
#     "4004":"其他骑行者(others)",
# "5000":"car",
#     "5001":"(有棚机动车)shed",
#     "5002":"(小型车)mini",
#     "5003":"轿车(car)",
#     "5004":"suv",
#     "5005":"大面包车/拉货面包车(minibus)",
#     "5006":"有棚非机动车(shed-non-motor)",
# "6000":"truck",
#     "6001":"带斗卡车(lorry)",
#     "6002":"异形车(machineshop)",
#     "6003":"箱形车(container)",
#     "6004":"皮卡",
#     "6005":"带斗大三轮",
# "7000":"bus",
#     "7001":"小巴(mini)",
#     "7002":"大巴(bus)",
#     "7003":"观光车(Sightseeing)",
# "8000":"obstacle",
#     "8001":"自主移动障碍物(removable)",
#     "8002":"不可自主移动障碍物(Resting)",
# "9000":"道路元素(sign)",
#     "9001":"锥桶(conebucket)",
#     "9002":"水马(waterhorse)",
#     "9003":"防撞桶(bullbarrel)",
#     "9004":"施工牌(construction)",
#     "9005":"警示三角牌(warning)",
# "10000":"noise",
#     "10001":"雨（含地面反弹）rain",
#     "10002":"snow",
#     "10003":"dust",
#     "10004":"fog",
#     "10005":"洒水车的水、车轮压过水池溅起的水花（water）",
#     "10006":"噪点(other_noise)",
#     "10007":"残影框excessive_layering",
# "11000":"other",
#     "11001":"other",
# "12000":"特种车（Special）",
#     "12001":"巡逻车 Patrolcar",
#     "12002":"清扫车 Sweeper",
#     "12003":"零售车 Retailcar",

# 映射到7类，使用细分类sublabel进行映射!!! TODO:需要适配4D自动标注模型生产的数据！！！！！
class_mapping_7 = {
    "1000": "pedestrian",     # 适配半自动
    "1001": "pedestrian",     # "直立的人(person)",
    "1002": "pedestrian",     # "形变的人(deformation)",
    "1003": "pedestrian",     # "带附着物的人(person_w_things)",
    "1004": "pedestrian",     # "复点位的人(person_inside)",
    "2000": "pedestrian",
    "2001": "pedestrian",     # "(推车的人)pushing",
    "3000": "bicycle",        
    "3001": "bicycle",        # "bicycle",
    "3002": "motorcycle",     # "motorcycle",
    "3003": "motorcycle",     # "tricycle",
    "3004": "motorcycle",     # "其他二轮三轮车(others)",  !!!!!!!!
    "3005": "motorcycle",     # "其他二轮三轮车(others)",  兼容处理
    "4000": "rider",
    "4001": "rider",          # "骑自行车的人(cyclist)",
    "4002": "rider",          # "骑摩托车的人(motorcyclist)",
    "4003": "rider",          # "骑三轮车的人(tricyclist)",
    "4004": "rider",          # "其他骑行者(others)",
    "5000": "car",
    "5001": "car",            # "(有棚机动车)shed",
    "5002": "car",            # "(小型车)mini",
    "5003": "car",            # "轿车(car)",
    "5004": "car",            # "suv",
    "5005": "car",            # "大面包车/拉货面包车(minibus)",
    "5006": "car",            # "有棚非机动车(shed-non-motor)",
    "6000": "truck",
    "6001": "truck",          # "带斗卡车(lorry)",
    "6002": "truck",          # "异形车(machineshop)",
    "6003": "truck",          # "箱形车(container)",
    "6004": "truck",          # "皮卡",
    "6005": "truck",          # "带斗大三轮",
    "7000": "bus", 
    "7001": "bus",            # "小巴(mini)",
    "7002": "bus",            # "大巴(bus)",
    "7003": "bus",            # "观光车(Sightseeing)",
    "8000": "ignore",
    "8001": "ignore",         # "自主移动障碍物(removable)",
    "8002": "ignore",         # "不可自主移动障碍物(Resting)",
    "9000": "ignore",
    "9001": "ignore",         # "锥桶(conebucket)",
    "9002": "ignore",         # "水马(waterhorse)",
    "9003": "ignore",         # "防撞桶(bullbarrel)",
    "9004": "ignore",         # "施工牌(construction)",
    "9005": "ignore",         # "警示三角牌(warning)",
    "10000": "ignore",
    "10001": "ignore",        # "雨（含地面反弹）rain",
    "10002": "ignore",        # "snow",
    "10003": "ignore",        # "dust",
    "10004": "ignore",        # "fog",
    "10005": "ignore",        # "洒水车的水、车轮压过水池溅起的水花（water）",
    "10006": "ignore",        # "噪点(other_noise)",
    "10007": "ignore",        # "残影框excessive_layering",
    "11000": "ignore",        # "other",
    "11001": "ignore",        # "other",
    "12000": "ignore",
    "12001": "ignore",        # "巡逻车 Patrolcar",
    "12002": "ignore",        # "清扫车 Sweeper",
    "12003": "ignore",        # "零售车 Retailcar",
}
classname2id_7 = {
    "car": 0,
    "truck": 1,
    "bus": 2,
    "rider": 3,
    "bicycle": 4,
    "pedestrian": 5,
    "motorcycle": 6,
    "ignore": 255,
}
class_name2refine_name = {
    "car": 'Vehicle',
    "truck": 'Truck',
    "bus": 'Truck',
    "rider": 'Cyclist',
    "bicycle": 'Cyclist',
    "pedestrian": 'Pedestrian',
    "person": 'Pedestrian',
    "motorcycle": 'Cyclist',
    "ignore": 255,
}
classname2id_refine = {
    "Vehicle": 1,
    "Cyclist": 2,
    "Pedestrian": 3,
    "Truck": 4,
    255: 255,
}
# 统一命名
index2name_map = class_mapping_7
# name2id_map = classname2id_7
name2id_map = classname2id_refine
id2name_map = {id: name for name, id in name2id_map.items()}
